### PR TITLE
Clean up and Asciidoctorj version change

### PR DESCRIPTION
**Pull request by danielgrycman**
Removed unused imports

### CODE REVIEW

**Comment by danielgrycman** [comment]
@jonbullock Any chance to get the build failure fixed? By the way when you are planning the release 2.5?

**Comment by jonbullock** [comment]
Thanks @danielgrycman - I try to keep up to date with the AsciidoctorJ releases and any other libraries in use with each release of JBake. 

The last time I looked the build failure was a Travis CI issue (see #251) who are looking into a solution. 

I don't have much spare time at the moment but I am trying to make small progress on the release of v2.5.0 each day. All I can say is ASAP at the moment,

**Comment by danielgrycman** [comment]
@jonbullock If you need help for the release just let me know :-).

**Comment by jonbullock** [comment]
Thanks I may take you up on that offer.

**Pull request merged**
