### PR TITLE
[WIP] migrate build to gradle

### PR DESCRIPTION
**Pull request by ancho**
I started a migration from maven to gradle based on issue #276 

Covered so far:
- [x] assembly
- [x] application distribution
- [x] local maven publishing with code signing
- [x] codecoverage with jacoco and publishing to coveralls

This is a work in progress. It shows the possibility to transform the maven build to gradle in a modularized way of configuration.

In the center is the main `build.gradle` file which is the root entry point for the build and handles the configuration of the dependencies for the project as well codecoverage with jacoco.

Running `gradlew jacocoTestReport` or the abbreviation `gradlew jTR` runs the tests and creates a test report which could be found afterward at `build/reports/jacoco/test/html/`.

It applies the coveralls gradle plugin to send the collected test data from jacoco to the coveralls webservice in combination with running the test reports.

See `.travis.yml` on how it is used in combination with travis-ci.

Furthermore it applies two local build scripts.
- gradle/application.gradle
- gradle/maven-publishing.gradle

The first is for bundling a distribution zip file. 

It uses the gradle application plugin to define the main entry point of the jbake cli and generate the appropriate run scripts for unix/linux and windows.
It uses grgit to clone the jbake example projects, bundle them and put them into the distribution package.

Executing `gradlew distZip` assembles the distribution package which could be found at `build/distributions/jbake-2.5.0-SNAPSHOT.zip`

To test the bundle you can execute `gradlew installDist`
It creates the distribution and places it unzipped into `build/install`.

Here is an example of how the structure looks like:

```
tree build/install/jbake/
build/install/jbake/
├── bin
│   ├── jbake
│   └── jbake.bat
├── example_project_freemarker.zip
├── example_project_groovy.zip
├── example_project_thymeleaf.zip
└── lib
    ├── args4j-2.0.26.jar
    ├── asciidoctorj-1.5.2.jar
    ├── asm-4.1.jar
    ├── asm-analysis-4.1.jar
    ├── asm-tree-4.1.jar
    ├── asm-util-4.1.jar
    ├── attoparser-1.3.jar
    ├── commons-collections-3.2.1.jar
    ├── commons-configuration-1.9.jar
    ├── commons-io-2.4.jar
    ├── commons-jexl-2.1.1.jar
    ├── commons-lang-2.6.jar
    ├── commons-lang3-3.1.jar
    ├── commons-logging-1.1.1.jar
    ├── commons-vfs2-2.0.jar
    ├── concurrentlinkedhashmap-lru-1.3.1.jar
    ├── freemarker-2.3.20.jar
    ├── groovy-2.4.1.jar
    ├── groovy-templates-2.4.1.jar
    ├── groovy-xml-2.4.1.jar
    ├── hamcrest-core-1.1.jar
    ├── jade4j-0.4.2.jar
    ├── javassist-3.16.1-GA.jar
    ├── javax.servlet-3.0.0.v201112011016.jar
    ├── jbake-core-2.5.0-SNAPSHOT.jar
    ├── jcommander-1.35.jar
    ├── jetty-continuation-8.1.12.v20130726.jar
    ├── jetty-http-8.1.12.v20130726.jar
    ├── jetty-io-8.1.12.v20130726.jar
    ├── jetty-server-8.1.12.v20130726.jar
    ├── jetty-util-8.1.12.v20130726.jar
    ├── jna-4.0.0.jar
    ├── jna-platform-4.0.0.jar
    ├── jruby-complete-1.7.16.1.jar
    ├── json-simple-1.1.1.jar
    ├── jul-to-slf4j-1.7.6.jar
    ├── junit-4.10.jar
    ├── logback-classic-1.1.1.jar
    ├── logback-core-1.1.1.jar
    ├── logging
    │   └── logback.xml
    ├── maven-scm-api-1.4.jar
    ├── maven-scm-provider-svn-commons-1.4.jar
    ├── maven-scm-provider-svnexe-1.4.jar
    ├── ognl-3.0.6.jar
    ├── orient-commons-1.6.4.jar
    ├── orientdb-core-1.6.4.jar
    ├── orientdb-nativeos-1.6.4.jar
    ├── parboiled-core-1.1.6.jar
    ├── parboiled-java-1.1.6.jar
    ├── pegdown-1.4.2.jar
    ├── plexus-utils-1.5.6.jar
    ├── regexp-1.3.jar
    ├── slf4j-api-1.7.7.jar
    ├── snappy-0.3.jar
    ├── thymeleaf-2.1.3.RELEASE.jar
    ├── thymeleaf-extras-conditionalcomments-2.1.1.RELEASE.jar
    └── unbescape-1.0.jar
```

The second build script is for the maven stuff.

It defines a custom POM description and defines two additional artifacts.
A `sources` jar and `javadoc` jar which get published along the main jar file.

Executing `gradlew install` publishes the jar's to your local maven repository.

```
tree ~/.m2/repository/org/jbake/jbake-core/2.5.0-SNAPSHOT/
/home/frank/.m2/repository/org/jbake/jbake-core/2.5.0-SNAPSHOT/
├── jbake-core-2.5.0-SNAPSHOT.jar
├── jbake-core-2.5.0-SNAPSHOT-javadoc.jar
├── jbake-core-2.5.0-SNAPSHOT.pom
├── jbake-core-2.5.0-SNAPSHOT-sources.jar
├── jbake-core-2.5.0-SNAPSHOT.tar
├── jbake-core-2.5.0-SNAPSHOT.zip
├── maven-metadata-local.xml
├── maven-metadata-sonatype-nexus-snapshots.xml
├── _maven.repositories
└── resolver-status.properties
```

It has a signing task to sign the artifacts based on the condition that the current version is a release Version (does not end with -SNAPSHOT) and has a uploadArchives task present.

Which is currently not the case. That is one of the open points I will discuss in a moment.

As you can see the basics are working. 

I had to change the way how the base path to locate the example projects is determined in the `FileUtil` class as the core jar is living besides the other libs in a lib/ directory relative to the distribution root directory. But it works. The application is working as expected.

So far so good.

There are some open tracks.
- [x] remote ~~maven~~ bintray publishing
- [x] binary distibution publishing

Currently the library is published to maven central if I get it right.
It is no problem to configure maven publish to upload the archive to maven central.
There is also a bintray plugin for publishing to bintray maven repositories. Which is my preferred target for library and binary distribution.

The question is, what does @jonbullock and the community want?

Thats a matter of taste. We can play around while sorting things out. One reason to open a WIP pull request ;)

I used the standard maven plugin for the maven part. There is also an incubating maven-publish plugin which is probably better suited for the remote publishing stuff.

I have not sorted out how to apply the migration process now. The proposal to wait until the open pull requests are applied is maybe the best idea.

At the end it is only a matter of changing and adding possible dependencies and its versions and copy the gradle build files to the project.

Oh. I forgot. I had to move the test resources into a relative directory to get the tests pass.
So all the test fixtures are now within `src/test/resources/fixture`.
There is some integration work to do as `this.getClass().getResource("/")` which is be used in the Tests does not point to the right directory during the tests.

See 48e3cb8

That is all for now.

### CODE REVIEW

**Comment by jonbullock** [comment]
Excellent work @ancho in answer to your question I do want to continue to publish to Maven Central and I'd like to start using Bintray as well.

I'll leave this open so we can carry on discussing it while the older PR's are dealt with.

**Comment by ancho** [comment]
Thank you Jon. I'll wait until you finished the heavy migration work for 2.5.0. Keep on merging! :smile:

There is an option to publish to bintray and sync to [sonatype maven central](https://bintray.com/docs/usermanual/uploads/uploads_syncingartifactswithmavencentral.html) and [jcenter](https://bintray.com/docs/usermanual/uploads/uploads_includingyourpackagesinacentralrepository.html).

**Comment by jonbullock** [comment]
Thanks for the link @ancho I'll try that for v2.5.0 at least for the artefact.

**Comment by ancho** [comment]
Congrats @jonbullock for the 2.5.0 release!
I merged with master and added the bintray plugin to the gradle build.

You can publish to bintray with 
`./gradlew bintrayUpload`

If you want to see what's going on without publishing
`./gradlew -PbintrayDryRun=true bU --info`

You need to add two properties to your local `gradle.properties` file.

* `bintrayUsername=username`
* `bintrayKey=secret`

It's possible to change the organization and repository too.
The properties are called `bintrayOrg` and `bintrayRepo`.
To publish to your private repository in an example repository run

`gradle -PbintrayOrg='' -PbintrayRepo=example bU`

To enable code signing you need to add some more properties to your local `gradle.properties` file:

* `signing.keyId=24875D73`
* `signing.password=secret`
* `signing.secretKeyRingFile=/Users/me/.gnupg/secring.gpg`

See https://docs.gradle.org/current/userguide/signing_plugin.html for more information

To skip signing on purpose add `-PskipSigning=true`

Next Step:

* [ ] add sdk vendor plugin (https://plugins.gradle.org/plugin/io.sdkman.vendors)

**Comment by ancho** [comment]
Added sdk vendor plugin.
Add the following properties to your local `gradle.properties` file:

* `sdkman_consumer_key=key`
* `sdkman_consumer_token=token`

And a little candy to the top. 
Run `./gradlew dependencyUpdates` to see outdated version of the current dependencies.

**Comment by jonbullock** [comment]
If I've read (and understood) correctly this is ready now? All outstanding items/tasks have been completed?

**Comment by ancho** [comment]
Hmm...I think I should merge with master first, to check version and dependency changes. But basically yes.

**Comment by ancho** [comment]
Ok. I merged with master, updated some gradle plugins and changed gradle wrapper to 3.3. 
[gradle requires jdk/jre 7 or higher](https://docs.gradle.org/current/userguide/installation.html#sec:prerequisites). We should remove the openjdk6 jdk from the travis build.
We produce 1.6 compatible bytecode:

```
 javap -v build/classes/main/org/jbake/app/Oven.class | grep -E 'minor|major'
  minor version: 0
  major version: 50
```

So it's just a requirement to build the project, not to use the library. What do you think @jonbullock ?

**Comment by jonbullock** [comment]
Fine with me, the plan is that v3 bumps up the required JRE to 7 (at least and maybe 8 depending on when it gets shipped) anyway. 

I'll have a play with this branch and get my head used to Gradle :)

Excellent work again though!

**Comment by ancho** [comment]
Thanks. I'll keep the branch warm, and merge with master from time to time....

**Comment by ancho** [comment]
Ahhh....and have fun :)

**Comment by ancho** [comment]
rebased to latest commit e1a749aa422acb8b99eb009b80cf24bb38e08ba3

**Comment by ancho** [comment]
rebased to latest commit e017d301a9857113b246f691f0a2cd736054b06a

**Pull request merged**
