### PR TITLE
Made ContentStore.java more redable

### PR DESCRIPTION
**Pull request by nikhilmudholkar**
instead of import specific files , I think it helps to import all class of a package. Also tried to style code in block structure in order to make it more readable. The earlier version of the code was very difficult to understand. Hope this helps.

### CODE REVIEW

**Comment by nikhilmudholkar** [comment]
can someone tell me why the check has failed? All i did was styling the code. Nothing else.

**Comment by ancho** [comment]
Hi, 

thanks your for your intention to make the code more readable.

I personally don't like that style. But that is a matter of taste. 
There is not really a styleguide yet. 
I adapt to the style of the project, and try to use common patterns.
 
And I prefer explicit imports over wildcard imports.

Where you able to compile the project after your change?
Like `mvn clean compile`

Your change misses to import classes from orientdb.
See https://travis-ci.org/jbake-org/jbake/jobs/181604835

<pre>
[ERROR] /home/travis/build/jbake-org/jbake/src/main/java/org/jbake/app/ContentStore.java:[37,12] error: cannot find symbol

[ERROR]   symbol:   class ODatabaseDocumentTx

  location: class ContentStore

/home/travis/build/jbake-org/jbake/src/main/java/org/jbake/app/ContentStore.java:[258,44] error: cannot find symbol

[ERROR]   symbol:   class OSchema

  location: class ContentStore

/home/travis/build/jbake-org/jbake/src/main/java/org/jbake/app/ContentStore.java:[44,17] error: cannot find symbol

[ERROR]   symbol:   class ODatabaseDocumentTx

  location: class ContentStore

/home/travis/build/jbake-org/jbake/src/main/java/org/jbake/app/ContentStore.java:[50,13] error: cannot find symbol

[ERROR]   symbol:   variable ODatabaseDocumentPool

  location: class ContentStore

/home/travis/build/jbake-org/jbake/src/main/java/org/jbake/app/ContentStore.java:[51,34] error: package ODatabaseRecordThreadLocal does not exist

[ERROR] /home/travis/build/jbake-org/jbake/src/main/java/org/jbake/app/ContentStore.java:[86,8] error: cannot find symbol

[ERROR]   symbol:   class OSchema

  location: class ContentStore
</pre>

If you really like wildcard imports that much you need to add wildcard imports for the missing packages, too.

I recommend to run `mvn test` before you open a pull request, to make sure your changes don't brake anything.

I hope that helps.

**Comment by nikhilmudholkar** [comment]
thanks,ancho. And sorry for if I caused some inconvenience. I am new to open source and i am finding it a bit complicated. Worry not, I will keep this in mind the next time.
Thanks

**Comment by ancho** [comment]
Hey @nikhilmudholkar. No worries. One step at a time. Just keep on.
What exactly is to complicated in your mind? Maybe we can change something, to make it easier.

**Comment by nikhilmudholkar** [comment]
There are quite a few doubts.
1. Do I have to make a separate branch for every change that i make in my local repository and then submit a pull request?
2. Where I can get very simple bugs? Like i am a beginner and would like to work on something that is very easy. 
3. Are there some issues related to documentation. If so, then how can I contribute to it?

**Comment by ancho** [comment]
> Do I have to make a separate branch for every change that i make in my local repository and then submit a pull request?

No. You do not have to. But it is a common practice to use branches for a special set of feature, fix or experiments, to keep the master clean. 

Here is a handful of Links that may help you.

* https://help.github.com/categories/collaborating-with-issues-and-pull-requests/ 
* http://nvie.com/posts/a-successful-git-branching-model/

> Where I can get very simple bugs? Like i am a beginner and would like to work on something that is very easy.

There is no such thing like a beginner or "low hanging fruit" category of issues.
But feel free to pick one of the issues and ask if things are unclear.
Use the milestones to find open tasks which are scheduled for the next release.
Or just dig into the code and open issues if you have ideas or catch parts of the code that need some love.

> Are there some issues related to documentation. If so, then how can I contribute to it?

The documentation is in the https://github.com/jbake-org/jbake.org repository.
There you may find documentation issues.

I hope that helps a bit.

**Comment by jonbullock** [comment]
@nikhilmudholkar It's great you're trying to improve the project, thanks for that. 👍 

I have to admit I much prefer braces on the same line, and if I ever get round to implementing a style guide that'll be the first thing I put in it. For this reason alone I won't be merging this PR in, but please don't let this stop you contributing to open source.

**Pull request closed without merging**
