### PR TITLE
Introduced Groovy MarkupTemplateEngine

### PR DESCRIPTION
**Pull request by ancho**
The Template Engine is registered for template files with suffix '.tpl'
It is basically a clone of GroovyTemplateEngine using the Groovy MarkupTemplateEngine.

Because there are refactoring pull-requests out there, I skipped refactoring those two Engines for now.

To unify the Renderer Tests for different TemplateEngines there is a new Spock-Test called RendererSpec.

### CODE REVIEW

**Comment by ancho** [comment]
thanks @melix for the clue. I didn't dive that deep but I'll reconsider it.

**Comment by jonbullock** [comment]
Thanks so much, I've wanted to add support for this for a while now!

**Comment by melix** [comment]
:+1:

**Comment by ancho** [comment]
You're welcome ;)
I'm working on an example-project. I'll let you know as soon as I have finished.

**Comment by ancho** [comment]
Hi. It's been a while, but I finally finished a example project using Groovy Markup Templates.
Have a look at https://github.com/ancho/jbake-example-project-groovy

To test the distribution I added a feature branch to.
See https://github.com/ancho/jbake/tree/feature/example-project-groovy-mte

**Comment by jonbullock** [comment]
Thanks again Frank, I've got some spare time again now so I'll make sure to review this as soon as possible and then work out when we can get it into a release.

**Comment by danhyun** [comment]
:+1:

**Comment by ancho** [comment]
+1

**Pull request merged**
