### PR TITLE
 Normalize whitespace - replace tabs with 4 spaces.

### PR DESCRIPTION
**Pull request by OndraZizka**
As per discussion at jbake-dev, let's normalize whitespace so it doesn't impose a burden to maintenance and cooperation. 
This only replaces the tabs, doesn't reformat.

I believe none of the tabs were significant, i.e. in test input files where it would make a difference.

This PR replaces PR #522 which had too many conflicts.

### CODE REVIEW

**Comment by ancho** [comment]
Reminds me to open a PR for checkstyle rules. See https://github.com/ancho/jbake/tree/feature/add-checkstyle-rules

**Comment by jonbullock** [comment]
Thanks @OndraZizka 👍

**Comment by jonbullock** [comment]
@ancho / @manikmagar any issue with this being included in 2.6.4 or will it cause issues with other larger PR's that are outstanding?

**Comment by ancho** [comment]
Hmmm....not for me. I need to rebase my open pr's anyways. That won't hurt much.

**Comment by manikmagar** [comment]
Not for me too, old pr's are due for rebasing.

**Comment by lefou** [comment]
Looks like a good chance to add a `.editorconfig` in the project root. See https://editorconfig.org/

**Comment by ancho** [comment]
Yes! See #372. I experimented with a simple set of checkstyle rules. https://github.com/ancho/jbake/blob/feature/add-checkstyle-rules/config/checkstyle/checkstyle.xml
Integrates perfectly with ide's. And we can integrate it into the build checks if we want.

Thanks for the reminder. I should open a PR for that.

**Pull request merged**
