### PR TITLE
fixed broken template engine unit tests

### PR DESCRIPTION
**Pull request by ancho**
The FreemarkerTemplateEngineRenderingTest failed. Fixed template files and refactored the AbstractTemplateEngineRenderingTest a bit.

### CODE REVIEW

**Comment by jonbullock** [comment]
Thanks @ancho

**Comment by jonbullock** [comment]
Long shot I know, but I don't suppose you remember what the test failed on do you?

**Comment by ancho** [comment]
We had common (duplicated) expectations on the rendered output for all template engines. I moved them to the AbstractTemplateEngineRenderingTest.

The Freemarker templates used different html elements which caused the FreemarkerTemplateEngineRenderingTest to fail.

But thinking it through it is maybe not the best idea to define a common set of expectations on the rendering output as it dictates the structure of all templates.

It's maybe better to change the expectations of the concrete Test.

**Comment by jonbullock** [comment]
The tests are dependant on the templates in the src/test/resources regardless and at the moment these tests are more integration tests to ensure the template engine code is working as expected. I'm happy to alter the structure when there is a need to test a different expectation of one of the template engines.

**Pull request merged**
