### PR TITLE
introduce DocumentModel and TemplateModel

### PR DESCRIPTION
**Pull request by ancho**
A little refactoring to introduce a kind of a model abstraction.

A DocumentModel is basically a HashMap with content specific content collected during crawling with explicit getters and setters.

A TemplateModel is a Hashmap with content needed during the rendering phase. It contains a DocumentModel as content.

From there on, we can extend the TemplateModel to add different kind of helper classes for use in different template engines.

### CODE REVIEW

**Comment by ancho** [comment]
Jup. Sounds like a plan.

**Comment by ancho** [comment]
Thanks for catching this. I'll fix it...

**Comment by jonbullock** [comment]
Not related to this PR but while reviewing this I couldn't help notice the number of String literals in the codebase, need to deal with them at some point.

**Comment by ancho** [comment]
> Not related to this PR but while reviewing this I couldn't help notice the number of String literals in the codebase, need to deal with them at some point.

Babysteps. It's getting better ;)

**Comment by jonbullock** [comment]
Yeah definitely 👍

**Comment by jonbullock** [comment]
Implemented via #533 (and ultimately via #700).

**Pull request closed without merging**
