### PR TITLE
#261 tests failing on windows

### PR DESCRIPTION
**Pull request by bark4mark**

### CODE REVIEW

**Comment by bark4mark** [comment]
I can't find a way to create a read only folder on windows, without reverting to running commands with a Runtime...

**Comment by jonbullock** [comment]
Thanks for raising this PR, I'll review fully once the next release is out.

**Comment by jonbullock** [comment]
Fixed as part of #349

**Comment by jonbullock** [comment]
There are new tests failing when run on Windows, but I'll raise a separate issue to address those.

**Pull request closed without merging**
