### PR TITLE
security update logback, other dependency updates + upgrade to gradle 7

### PR DESCRIPTION
**Pull request by ancho**
As the distribution package of jbake does deliver a writable logback.xml
we need to fix this immediatly.

See https://jira.qos.ch/browse/LOGBACK-1591 and [News from 14th of December](http://logback.qos.ch/news.html)

### CODE REVIEW

**Comment by kwin** [comment]
Meanwhile Logback 1.2.10 has been released which contains more hardening against potential attacks.

**Comment by ancho** [comment]
Thanks for the hint.

**Review by jonbullock — APPROVED** [review]

**Comment by jonbullock** [comment]
Good catch, thanks @ancho

**Comment by ge0ffrey** [comment]
Partially obsolete due to https://github.com/jbake-org/jbake/pull/740, Ancho is working on a security update logback separate PR

**Comment by jonbullock** [comment]
I'm AFK at the moment but if this is ready to merge in feel free to do so @ancho

**Comment by ancho** [comment]
Allright then. I think it's ready now.

**Pull request merged**
