### PR TITLE
Add test case into ParserTest.java

### PR DESCRIPTION
**Pull request by AliZDev-v0**

### CODE REVIEW

**Comment by Ali96kz** [comment]
Could somebody help me with travis-ci?

**Comment by ancho** [comment]
Try to rebase with jbake upstream. There is a fix for travis builds on jdk9. See #433 and #447 for details.

**Comment by Ali96kz** [comment]
@ancho Thanks, worked for me

**Comment by Ali96kz** [comment]
Ready for review

**Pull request merged**
