### PR TITLE
Add dependabot configuration

### LINKED ISSUE #626: Enable dependabot (or similar) to manage dependencies?
Should we enable [Dependabot](https://dependabot.com/#how-it-works) or similar to manage dependencies? This will help to keep dependencies up to date.

### PR DESCRIPTION
**Pull request by manikmagar**
1. Prerequisite - Dependabot permission needs to be granted to jbake-org/jbake repo.
2. This PR adds dependabot configuration for both modules in this repo.

Fixes #626

### CODE REVIEW

**Comment by manikmagar** [comment]
Job failed to download gradle. Could be a temporary issue? Can the job be re-triggered?

```
Downloading https://services.gradle.org/distributions/gradle-5.2.1-bin.zip
Exception in thread "main" java.net.UnknownHostException: downloads.gradle-dn.com

```

**Comment by ancho** [comment]
hm....job failed. and why is travis ci not listed in the checks anymore?
double checked. is not listet on my last pr as well :woman_shrugging:

**Comment by manikmagar** [comment]
Looks like Travis ran but did not report on the PR - https://travis-ci.org/github/jbake-org/jbake/builds/668378245. Maybe checks reporting is broken?

**Comment by manikmagar** [comment]
Pushed empty commit to re-trigger jobs.

**Comment by manikmagar** [comment]
@jonbullock Can you also please enable Dependabot on this repo, if not done already? Thanks!

> Prerequisite - Dependabot permission needs to be granted to jbake-org/jbake repo.

**Comment by jonbullock** [comment]
@manikmagar I did that prior to merging this yesterday. 

This is what I see: 
Screenshot 2020-04-13 at 15 28 24

**Comment by manikmagar** [comment]
Awesome! Thanks. Looks good.

**Pull request merged**
