### PR TITLE
Pagination

### PR DESCRIPTION
**Pull request by jasondlee**
This seems to do the trick. I'm currently using it to publish my blog. :)

I added a test for Freemarker in this is as well. While not directly related, certainly helpful. I think the template engine tests can be refactored further to reduce the amount of duplication, but that's a task for another branch.

### CODE REVIEW

**Comment by jonbullock** [comment]
Excellent! I'll be reviewing all the outstanding PR's soon and getting them merged or scheduled to be merged.

Thanks again.

**Comment by jasondlee** [comment]
Any update on this? :)

**Comment by jonbullock** [comment]
Apologies Jason I got snowed under, so in answer to your question, no :(

But I've got some spare time again so I'll get back onto it soon.

**Comment by jasondlee** [comment]
No worries. Just checking in. :)

On 5/5/15 7:13 AM, Jonathan Bullock wrote:
>
> Apologies Jason I got snowed under, so in answer to your question, no :(
>
> But I've got some spare time again so I'll get back onto it soon.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/jbake-org/jbake/pull/186#issuecomment-99063349>.
>

-- 
Jason Lee
http://cubtracker.com
http://blogs.steeplesoft.com
http://twitter.com/jasondlee
http://blogs.steeplesoft.com/+
http://blogs.steeplesoft.com/in

**Comment by jonbullock** [comment]
Started to merge this in and noticed you added the 'freemarkerTemplates' folder. Is this a copy of the existing 'templates' folder? Or a new set of templates specific to this PR?

**Comment by uli-heller** [comment]
If you need help on GSP templates, I'm volunteering in helping onr this. I like the paging approach, I'm using GSP templates and I do have a little bit of  free time for the next weeks.

**Comment by jonbullock** [comment]
Thanks for the offer... I'm in the middle of merging in all the outstanding PRs for 2.5.0 including this one... so it'll take a bit of time before I commit back. What kind of help where you thinking of?

**Comment by uli-heller** [comment]
Looking at the patch, I see some changes to the FTL templates. I think I could "port" these changes to the GSP templates, or test the patches using GSP templates, or fix some bugs within the templates and within the engines (at work, I'm a java developer).

**Comment by jasondlee** [comment]
It's been a while, but, iirc, those are new files specifically for the 
FreemarkerRendererTest added in this PR.

On 6/7/15 3:50 PM, Jonathan Bullock wrote:
>
> Started to merge this in and noticed you added the 
> 'freemarkerTemplates' folder. Is this a copy of the existing 
> 'templates' folder? Or a new set of templates specific to this PR?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/jbake-org/jbake/pull/186#issuecomment-109798745>.
>

-- 
Jason Lee
http://cubtracker.com
http://blogs.steeplesoft.com
http://twitter.com/jasondlee
http://blogs.steeplesoft.com/+
http://blogs.steeplesoft.com/in

**Comment by jonbullock** [comment]
Thanks Jason, I haven't forgotten about this, I did start to merge this in manually and started a list of clean up jobs for after the merge is complete. However, my recent new arrival has meant I've just had no spare time to carry on with it, hopefully soon I'll get chance to finish off the merge.

**Pull request merged**
