### PR TITLE
update dependencies and gradle wrapper

### PR DESCRIPTION
**Pull request by ancho**
Update gradle wrapper to 6.1.1
Moved versions configuration to `gradle.properties` and replaced deprecated dependency configurations. See [Java dependency management overview](https://docs.gradle.org/current/userguide/building_java_projects.html#sec:java_dependency_management_overview)

Updated dependencies:

* asciidoctorj 1.5.8.1 -> 2.2.0
* asciidoctorj-diagram 1.5.11 -> 2.1.0
* commons-vfs2 2.2 -> 2.6.0
* commons-lang 3.8.1 -> 3.9
* freemarker 2.3.28 -> 2.3.29
* flexmark 0.40.8 -> 0.60.2
* groovy 2.5.5 -> 3.0.0
* jetty-server 9.4.12.v20180830 -> 9.4.26.v20200117
* jgit 5.2.1.201812262042-r -> 5.6.0.201912101111-r
* jsoup 1.11.3 -> 1.12.2
* orientdb 3.0.14 -> 3.0.28
* pebble 3.0.7 -> 3.1.2
* assertj 2.9.1 -> 3.15.0
* junit5 5.3.1 -> 5.6.0
* junit-pioneer 0.2.2 -> 0.5.3
* slf4j 1.7.25 -> 1.7.30
* mockito 2.23.4 -> 3.2.4

Updated gradle plugins:

* com.github.ben-manes.versions 0.20.0 -> 0.27.0
* nebula.optional-base 5.0.0 -> 5.0.3
* io.sdkman.vendors 1.1.1 -> 1.2.1
* com.github.kt3k.coveralls 2.8.2 -> 2.9.0

### CODE REVIEW

**Comment by jonbullock** [comment]
Thanks @ancho

**Comment by jonbullock** [comment]
We had this scheduled in for v2.7.0, any reason it can't be included in v2.6.5?

**Comment by ancho** [comment]
Hey Jon....no ;)

**Comment by ancho** [comment]
squash in progress....

**Comment by jonbullock** [comment]
Thanks @ancho 👍

**Pull request merged**
