### PR TITLE
Added support for Pebble template engine

### PR DESCRIPTION
**Pull request by mbosecke**
I'm not sure if you guys are interested but I added support for a template engine called [Pebble](http://www.mitchellbosecke.com/pebble).

### CODE REVIEW

**Comment by jonbullock** [comment]
I'm very interested in adding support for Pebble so thanks for the contribution. Support will probably be included in the v3.0.0 release.

**Comment by jonbullock** [comment]
I didn't notice that Pebble requires JDK7 so I'm going to revert the merge until JDK7 support is added, will probably be the next release though.

**Comment by decebals** [comment]
I need this template. I think that nowadays Java 7 is the minimum version. I don't understand why jbake is based on Java 6.

**Comment by jonbullock** [comment]
Don't worry Java 7 is on horizon and support for Pebble will be re-introduced.

**Pull request merged**
