### PR TITLE
WIP: Rework commandline

### PR DESCRIPTION
**Pull request by lefou**
This pull reqest replaces the cmdline parser with CmdOption. I also started to eliminate System.exit() calls from various places. This makes it easier to run JBake as library. The command line parser is used to populate the configuration. With that configuration an instance of the Main class is created. Calls to it's non-static methods will not call System.exit() but will throw a JBakeException in case of an error.

I removed the printUsage() method from Main, as this is now completely rendered by CmdOption. Please note, that is very easy to provide translated versions of it. If you are interested in it, I could create a German translation for it.

WDYT?

### CODE REVIEW

**Comment by lefou** [comment]
Do we want to discuss that issue over IRC tonight?

**Comment by jonbullock** [comment]
Sorry only just seen this, are you available tonight?

I'll be on IRC anyway tonight just in case.

**Comment by lefou** [comment]
Hi @jonbullock, I try to make it tonight. In the meantime I decided to decouple the System.exit part and sent you a new PR #168.

**Comment by jonbullock** [comment]
I'm merging in all the pull requests for v2.5.0 and I've got to this one, before I do anything I wanted to check whether this was ready to be merged or was there more to be included?

**Comment by lefou** [comment]
Hi Jonathan,
I'd say, at time of request it was complete, but I marked it as WIP as I shamelessly replaced the existing cmdline parser with another one I wrote be myself. I vaguely remember, that you once said you want to overhaul and replace the parsing.
As the request is more that two years old, JBake might have changed, e.g. more cmdline options, other structure. Also, parts of this PR already found their way into JBake, namely the elimination of `System.exit()` calls and the `JBakeException`. So, I wouldn't merge in this state.

If you are interested in an cmdline overhaul and you like what you see (in terms of the choosen cmdline parser [CmdOption](https://github.com/ToToTec/CmdOption)), let us discuss it and I will prepare an update.

**Comment by jonbullock** [comment]
Ah OK I'll close this PR off then.

Yes I do want to look at overhauling the CLI and I'm happy to look at using CmdOption. We can look at doing this once v2.5.0 is out.

**Pull request closed without merging**
