### PR TITLE
Release/2.6.6

### PR DESCRIPTION
**Pull request by ancho**
Combines PR's from the [2.6.6 milestone](https://github.com/jbake-org/jbake/milestone/21)

#648, #643 and #644

### CODE REVIEW

**Comment by ancho** [comment]
I don't understand what is going on at travis-ci. For some reasons all linux test stages fail while the mac  os stages are green.

Build and tests run fine on my local machine.
The travis build on my local repository is all green https://travis-ci.org/github/ancho/jbake/builds/724457110

I cleared the cache rerun it several times. Needs some investigation but it's not that easy to debug to be honest.

**Comment by ottlinger** [comment]
@ancho maybe the build should be updated to Ubuntu 20.x?! BTW: jBake seems to run on travis-ci-org, which is going to be shutdown and merged into travis-ci.com

**Comment by ancho** [comment]
;)
hehe. just did that in another branch. https://travis-ci.org/github/ancho/jbake/builds/758906274
but focal at travis does not support openjdk 8 anymore.

**Comment by ancho** [comment]
> @ancho maybe the build should be updated to Ubuntu 20.x?! BTW: jBake seems to run on travis-ci-org, which is going to be shutdown and merged into travis-ci.com

Jup. Just noticed that. There is a lot todo in this project. Travis-ci is the smallest problem in line. Bintray shutdown worries me more.

**Comment by ancho** [comment]
This is pure madness. travis-ci documentation is irritating. if you use bionic you have access to openjdk8 which currently delivers version 1.8.0_242 and the build fails. If i run the build in an ubuntu:bionic container installing openjdk-8-jdk-headless the build runs fine.

As of the documentation focal supports openjdk8 https://docs.travis-ci.com/user/reference/focal/#jvm-clojure-groovy-java-scala-support

> Pre-installed JVMs: openjdk8,openjdk10, and openjdk11 on x86, default is openjdk11.

But that's not even true. 

```
Installing openjdk8

$ export JAVA_HOME=~/openjdk8

$ export PATH="$JAVA_HOME/bin:$PATH"

$ ~/bin/install-jdk.sh --target "/home/travis/openjdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "GPL" --cacerts

Ignoring license option: GPL -- using GPLv2+CE by default

install-jdk.sh 2020-06-02

Expected feature release number in range of 9 to 17, but got: 8
```

See https://travis-ci.com/github/ancho/jbake/jobs/482900384

It also says you can use the jdk_switcher which is not true for bionic (thought maybe i get a newer jdk8 bundle) but not. I got this:

```
$ jdk_switcher use openjdk8

jdk_switcher: command not found

The command "jdk_switcher use openjdk8" exited with 127.
```

See https://travis-ci.com/github/ancho/jbake/jobs/482899771

That's to much pain for a relaxed sunday afternoon for me.

**Comment by ottlinger** [comment]
@ancho +1 for the proposed solution to cancel JDK8.
I had a lots of issues with JDK8 on Travis with other projects (Apache RAT) - the JDK-selection does not seem to work properly, resulting in build failures if you want to ensure e.g. that a JDK8 build contains only JDK8-artifacs, but I assume this does not apply for jBake.

**Comment by jonbullock** [comment]
Great work @ancho I've ran out of time to review  and merge this tonight but I'll get to it tomorrow, if not over lunch then it'll be in the evening.

**Review by jonbullock — APPROVED** [review]

**Pull request merged**
