### PR TITLE
Support for jade template engine

### PR DESCRIPTION
**Pull request by mariuszs**

### CODE REVIEW

**Comment by jonbullock** [comment]
I've just invited you to a team in the JBake organisation here so we can arrange to move the example project repo here if that's OK with you?

**Comment by mariuszs** [comment]
Yes, this is ok for me.

**Comment by jonbullock** [comment]
Excellent, could you try transferring the repo over to the jbake organisation and let me know how you get on? GitHub has changed it's security model since I last tried this.

**Comment by mariuszs** [comment]
I have tried without success. Please create repository and give me temporary admin access

**Comment by mariuszs** [comment]
example-project-team
> This team does not give members access to specific repositories.

**Comment by jonbullock** [comment]
OK you should have write access to the repo (jbake-example-project-jade) now.

**Pull request closed without merging**
