### PR TITLE
adjust jvmargs. fix compile warnings.

### PR DESCRIPTION
**Pull request by ancho**
add MaxDirectMemorySize to jdk9 compatible build

it is unable to determine the amount of MaxDirectMemorySize running in a
travis docker environment. See https://pastebin.com/ECvQeHx0

### CODE REVIEW

**Comment by jonbullock** [comment]
Hmm it was the JDK7 build on AppVeyor that failed with an out of memory (permgen) issue this time:

https://ci.appveyor.com/project/jbake-org/jbake/build/95/job/jvlfuhmdl725axxb#L2318

**Comment by ancho** [comment]
hmm. Are you able to trigger a rebuild on appveyor?

**Comment by jonbullock** [comment]
Yeah just kicked it off now.

**Comment by jonbullock** [comment]
All green 👍

**Pull request merged**
