### PR TITLE
Upgrade Gradle from 5 to 6

### PR DESCRIPTION
**Pull request by georgecao**
Gradle 6 support JDK 13 officially, so to fix https://travis-ci.org/jbake-org/jbake/jobs/657847273?utm_medium=notification&utm_source=github_status, upgrade Gradle to **6.2.1** by ` ./gradlew wrapper --gradle-version 6.2.1`

### CODE REVIEW

**Comment by georgecao** [comment]
@acanda @jonbullock could you review this?

**Comment by georgecao** [comment]
@acanda @jonbullock could you review this?

**Comment by acanda** [comment]
Hi George, thank you for your contribution. I'm not involved in JBake so I leave it to Jon to review this.

**Comment by ancho** [comment]
hi. thank you very much. an update of all dependencies including gradle is part of #603

**Comment by georgecao** [comment]
> hi. thank you very much. an update of all dependencies including gradle is part of #603

OK, I close this one. Thanks.

**Comment by georgecao** [comment]
#603 covers this one, so close this one.

**Pull request closed without merging**
