### PR TITLE
Update to OrientDB 3.1.16 to support Apple Silicon

### PR DESCRIPTION
**Pull request by kwin**
https://github.com/orientechnologies/orientdb/pull/9762

### CODE REVIEW

**Comment by kwin** [comment]
I experience local test failures both in latest master and in this PR, so not sure this introduces regressions.

**Comment by jbaron** [comment]
Have same problem (see error below), but not a problem if I just upgrade the version at runtime (see also my comment at #709) 


```
com.orientechnologies.orient.core.exception.ODatabaseException: Invalid database name:'/var/folders/sn/pw3sb44d14g1g3_t1xh4_qlr0000gn/T/junit16331792743401417938/documents1660680832696'
            at app//com.orientechnologies.orient.core.db.OrientDBEmbedded.checkDatabaseName(OrientDBEmbedded.java:1113)
            at app//com.orientechnologies.orient.core.db.OrientDBEmbedded.create(OrientDBEmbedded.java:613)
            at app//com.orientechnologies.orient.core.db.OrientDB.createIfNotExists(OrientDB.java:269)
            at app//com.orientechnologies.orient.core.db.OrientDB.createIfNotExists(OrientDB.java:256)
            at app//org.jbake.app.ContentStore.startup(ContentStore.java:95)
```

**Comment by kwin** [comment]
Superseded by #365.

**Comment by jonbullock** [comment]
@jbaron The tests use a path as the DB name and OrientDB v3.1.x has an issue with the slashes, which v3.0.x didn't. This isn't a problem in 99% of real life scenarios where the DB name will most likely be "cache". While the upgrade to v3.1.x is pretty seamless it does require a change to JBake relating to the retrieval of tags.

Thanks @kwin for looking into this and raising the PR in the first place.

**Pull request closed without merging**
