### PR TITLE
replace pegdown with felxmark-java

### PR DESCRIPTION
**Pull request by ancho**
See #327

### CODE REVIEW

**Comment by jonbullock** [comment]
Thanks @ancho looks like this new lib delivers some serious performance gains.

**Comment by bdelacretaz** [comment]
FWIW, for people experimenting with this on existing content, https://github.com/vsch/flexmark-java includes a "Pegdown Migration Helper" section.

**Comment by kwin** [comment]
Would you reconsider integrating this really useful change into the next i.e. 2.6.0 version?

**Comment by jonbullock** [comment]
Yeah we'll include this in the 2.6.0 release.

**Pull request merged**
