### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by bodiam**
Cleanup of some code by removing a lot of duplication and some unused code.

### CODE REVIEW

**Comment by haumacher** [comment]
Please do not merge this, reformatting the code would render all other branches/forks of JBake unmergable!

**Comment by bodiam** [comment]
I don't agree. If you want to discuss this, please open an issue so we can discuss it in a central place instead of on 3 separate issues.

**Comment by haumacher** [comment]
This is not a separate issue. I just want to vote against merging your changes which all 3 include a completely reformatted code base. See also https://github.com/jbake-org/jbake/pull/238#issuecomment-154873223

My experience is that reformatting code makes merging extremely hard. If you think I'm wrong, you could try to rebase e.g. https://github.com/haumacher/jbake/tree/wikibake.1 on your reformatted code base.

**Comment by lefou** [comment]
Please isolate the clean-ups from the code format changes (#238).

**Pull request closed without merging**
