### PR TITLE
 paginate into subfolders

### PR DESCRIPTION
**Pull request by ancho**
The first index.html is rendered into the root directory.
Following paginated pages are put into subfolders per page like 1/index.html, 2/index.html etc.

### CODE REVIEW

**Comment by jonbullock** [comment]
Great work again @ancho  👍 

Could you separate out the fix for #310 into a separate PR? 

As I'm planning on releasing 2.5.1 to fix a few things.

**Comment by ancho** [comment]
Thanks. What do you mean by that? This one is on top of #310. So if you just want to fix the pagination stuff with the variables, you should be able to merge this one afterwards.

**Comment by jonbullock** [comment]
I saw commit 2822cfc being as part of this PR so thought it included the fix for #310 as well as the new feature for allowing you paginate into subfolders.

**Comment by ancho** [comment]
I knew there was something missing. This PR was one commit behind #312. So i forced to include b257126 to prevent a merge conflict.

**Pull request merged**
